.\" Process this file with
.\" groff -man -Tascii voacapl.man
.\"
.TH VOACAPL 1 "SEO 2013" Linux "User Manuals"
.SH NAME
dst2csv \- Convert DST record files to CSV
.SH SYNOPSIS
.B dst2csv
.br
.B dst2csv -i dst_directory
.br
.B dst2csv -d -i dst_directory
.br
.SH DESCRIPTION
This is a small utility to convert the binary record file produced when performing
distance calculations to a CSV file for further processing.
.br
Distance calculations are triggered by performing by using the filenames
voacapd.dat and voacapd.out for voacap input/output files. e.g.
.br
voacapl ~/itshfbc voacapd.dat voacapd.out
.br
.SH OPTIONS
.IP dst_directory
The location of the .dst file and corresponding .idx file.  The output csv file
is saved in this directory.  If this parameter is not specified, the current
working directory will be used.
.SH EXAMPLES
dst2csv
.br
Creates a CSV files (voacapd.csv) using the values found in the voacap.dst and
voacapd.idx files located in the current working directory.
.br
dst2csv -i my_directory
.br
Creates a CSV file (my_directory/voacapd.csv) using the values found in the
voacap.dst and voacapd.idx files located in the directory 'my_directory'.
.br
dst2csv -d -i my_directory
.br
Creates a CSV file (my_directory/voacapd.csv) using the values found in the
voacap.dst and voacapd.idx files and a 'dump' file (my_directory/voacapd.dmp)

.SH FILES
.I voacapd.dst voacapd.idx
.RS
dst2csv requires access to the dst and corresponding index (.idx) files to run.

.SH ENVIRONMENT
dst2csv does not make use of any environment variables.
.SH AUTHOR
James Watson <jimwatson at mac dot com>.
.SH "SEE ALSO"
www.voacap.com
