.\" (C) Copyright 2024 David da Silva Polverari <polverari@debian.org>
.TH VOACAPL 1 "February  12 2024" "Debian Project"
.SH NAME
makeitshfbc \- creates the itshfbc directory structure in current user's home directory
.SH SYNOPSIS
.B makeitshfbc
.SH DESCRIPTION
.PP
\fBmakeitshfbc\fP  creates a local copy of the itshfbc/ directory structure in
the current user's home directory.
.SH AUTHORS
.PP
makeitshfbc was written by James Watson <jimwatson@mac.com>.
.LP
This manual page was written by David da Silva Polverari <polverari@debian.org>
for the Debian Project (but may be used by others).
.SH SEE ALSO
.BR voacapgui (1),
.BR voacapl (1)
