c###outgph.for
      SUBROUTINE OUTGPH
C--------------------------------
C
C     THIS ROUTINE CALLS SUBROUTINES TO SETUP AND OUTPUT LINE GRAPHS
C
      COMMON /OUTPRT/ LINBOT(26), LINBD(14), LINTOP(15), LINTP(14),
     A GRPTYP, JOUT, LINBYP, LINES, LINMAX, LINTYP, LPAGES, NLINE
      LINES = 0
C.....CALL SUBROUTINE OUTTOP TO OUTPUT THE HEADER LINES
      CALL OUTTOP
C.....CALL SUBROUTINE SETGPH TO SET THE VARIABLES TO BE PLOTTED
      CALL SETGPH
C.....CALL SUBROUTINE GPHBOD TO PRODUCE LINE PRINTER GRAPHS
      CALL GPHBOD
      RETURN
      END
C--------------------------------
