c###outtab.for
      SUBROUTINE OUTTAB
C--------------------------------
C.....THIS ROUTINE TABULATES THE VARIABLE TO BE TABULATED WITH ALLMUF
C.....VS. FREQUENCY IN SUBROUTINE TABBOD
      COMMON / OUTGH / PLOTI(24), PLOTJ(24), PLOTK(24), XOUT(13), NPLOTS
      COMMON / OUTPRT / LINBOT(26), LINBD(14), LINTOP(15), LINTP(14),
     A GRPTYP, JOUT, LINBYP, LINES, LINMAX, LINTYP, LPAGES, NLINE
      COMMON / SON / ANGLE(13), ANGLER(13), CPROB(13), DBLOS(13),
     A DBLOSL(13), DBLOSU(13), DBU(13), DELAY(13), DBW(13), NHP(13),
     B XNYNOIS(13), PROBMP(13), RELIAB(13), SNDB(13), SNPR(13),
     C SNRLW(13), SNRUP(13), SPROB(13), VHIGH(13), RNEFF(13),MDL(13)
       CHARACTER MDL*1
C.....SET THE VARIABLE TO BE TABULATED DEPENDENT OF METHOD
      DO 120 I = 1,13
  120 XOUT(I) = RELIAB(I)
C.....PRINT TOP OF PAGE INFORMATION IF FIRST TIME IN HOUR LOOP
      IF(LINES.ge.LINMAX) then
         CALL OUTTOP
         LINES=9            !  fake for TABBOD
      end if
      CALL TABBOD
      RETURN
      END
C--------------------------------
