c###tabs.for
      SUBROUTINE TABS(DEL,HP,DM,AM)
C--------------------------------
C
C     THIS SUBROUTINE CALCULATES THE LOSS PER KILOMETER FOR THE
C     PART OF THE PATH THAT MISSES THE ABSORBING REGINON
C
      COMMON/FRQ/FREA(13),FREL(29),FREQ,JMODE,ITXRCP(2)
      COMMON/CON/D2R,DCL,GAMA,PI,PI2,PIO2,R2D,RZ,VOFL
      COMMON/GEOG/GYZ(5),RAT(5),GMDIP(5),CLCK(5),ABIY(5),ARTIC(5),SIGPAT
     A(5), EPSPAT(5)
      IF(DM) 110,110,105
  105 IF(HP-70.) 110,110,115
  110 AM = 1000.
      RETURN
C.....ABSORPTION INDEX
  115 XI = 0.1
C.....THIS IS THE F2 MODE LOSS FOR A FRACTIONAL NUMBER OF HOPS
      AB  = 10.2 + (FREQ +GYZ(3))  **1.98
      AM  = 677.2 * XI/AB
      RCOSD = RZ*COS(DEL)
      SPHE  = RCOSD/(RZ+HP)
      PHE   = ATAN(SPHE/SQRT(1.-SPHE*SPHE))
      PSI   = PIO2 -PHE - DEL
      XMHOP = .5* DM/PSI
      SPHE  = RCOSD/(RZ+100.)
      SCPHE = 1./SQRT(1.-SPHE*SPHE)
      PORT  = XMHOP* SCPHE/(DM*RZ)
      AM  = AM*PORT
      RETURN
      END
C--------------------------------
