      SUBROUTINE ANOIS1(RLMT,RLAT,RLONG)
C.....VERSION 03.NOV.92 (input lat,long now in radians)
C.....A ROUTINE THAT USES RLMT TO DETERMINE THE TIMEBLOCK (KJ)
C.....AND ADJACENT TIME BLOCK (JK) (THIS IS THE PRIOR TIMEBLOCK
C.....FOR THE FIRST 2 HOURS OF KJ, THE SAME, IE JK=KJ, FOR THE 3RD
C.....HOUR OF KJ AND THE NEXT TIME BLOCK FOR THE LAST HOUR OF KJ)
C.....AND THEN CALLS NOISY TO FIGURE THE ATMOSPHERIC NOISE (ATNU
C.....OR ATNY) FOR EACH OF THESE TIME BLOCKS.
C.....
C.....THIS ROUTINE DETERMINES THE 1 MHZ ATMOSPHERIC NOISE
C.....
C.....FOURIER SERIES IN LATITUDE AND LONGITUDE FOR TWO DISCRETE
C.....LOCAL TIME BLOCKS
C.....
      COMMON /NOISE/ ATNOS,GNOS,XNOIS,SFA,ATNU,ATNY,CC,TM,KJ,JK
      DATA R2D/57.295779513/
C.....LMT AT RCVR SITE
ccc      write(16,'('' in ANOIS1='',3f11.5)') rlmt,rlat,rlong
 100  CC = RLMT
      KJ= 6
      IF(CC-22.) 105,110,110
 105  KJ = CC/4. +1.
 110  TM = 4*KJ-2
      IF(CC-TM) 115,120,125
 115  JK = KJ -1
      GO TO 130
 120  JK = KJ
      GO TO 130
 125  JK = KJ+1
 130  IF(JK) 135,135,140
 135  JK =6
      GO TO 150
 140  IF(JK-6) 150,150,145
 145  JK = 1
C.....EAST LONGITUDE, CEG(IN DEGREES)
 150  CEG= RLONG*R2D
      ceg=-ceg        !  correct because RLONG has west = + !!
      if(ceg.lt.0.) ceg=ceg+360.
 165  XLA =RLAT*R2D
C.....LATITUDE, XLA (IN DEGREES) "+" IS NORTH
ccc      write(16,'('' beofre NOISY='',2i5,2f10.4)') kj,jk,xla,ceg
      CALL NOISY(KJ,XLA,CEG,ATNU)
      CALL NOISY(JK,XLA,CEG,ATNY)
ccc      write(61,'('' In anois1='',4f10.4)') xla,ceg,atnu,atny
      RETURN
      END
