c###blkdat.for
C  /CON/  CONSTANTS
C              DCL  : 1.28
C              GAMA : 0.57721566  (EULER'S CONSTANT)
C              PI   : 3.1415926
C              PI2  : 2*PI = 6.283185307
C              PIO2 : PI/2 = 1.570796326
C              R2D  : PI/180 =0.01745329251
C              D2R  : 180/PI = 57.295779513
C              RZ   : EARTH'S RADIUS = 6371 KM
C              VOFL : SPEED OF LIGHT IN 1000KM/S =299.79246
C  /DON/ GENERAL GEOGRAPHIC VARIABLES
C              AMIN    : MINIMUM TAKE-OFF VALUE FOR TRANSMITTER ANTENNA
C              AMIND   : MINIMUM VALUE OF TAKE-OFF ANGLE IN DEGREES (DG)
C              BTR     : TRANSMITTER-RECEIVER AZIMUTH IN RADIANS
C              BTRD    : TRANSMITTER-RECEIVER AZIMUTH IN DEGREES
C              BRTD    : RECEIVER-TRANSMITTER AZIMUTH IN DEGREES
C              GCD     : DISTANCE BETWEEN TRANSMITTER AND RECEIVER IN RD
C              GCDKM   : DISTANCE BETWEEN TRANSMITTER AND RECEIVER IN KM
C              PWR     : TRANSMITTER POWER IN KW
C              PWRDB   : TRANSMITTER POWER IN DB
C              RLAT    : RECEIVER GEOGRAPHIC LATITUDE IN RD
C              RLATD   : RECEIVER GEOGRAPHIC LATITUDE IN DG
C              RLONG   : RECEIVER GEOGRAPHIC LONGITUDE IN RD
C              RLONGD  : RECEIVER GEOGRAPHIC LONGITUDE IN DG
C              SSN     : SUNSPOT NUMBER
C              TLAT    : TRANSMITTER GEOGRAPHIC LATITUDE IN RADIANS
C              TLATD   : LATITUDE OF TRANSMITTER IN DEGREES
C              TLONG   : LONGITUDE OF TRANSMITTER IN RADIANS
C              TLONGD  : LONGITUDE OF TRANSMITTER IN DEGREES
C              PGLAT   : GEOMAGNETIC LATITUDE OF PATH MID-POINT IN RADS
C              PLAT    : LATITUDE OF PATH MID-POINT (RADIANS, +N)
C              PLONG   : LONGITUDE OF PATH MID-POINT (RADIANS, +W)
C              ACAV    : AVERAGE VALUE OF ABSORPTION INDEX
C              ASMNG   :
C              FEAV    : AVERAGE VALUE OF foE
C              GMT     : UNIVERSAL TIME
C              VERSN   : PROGRAM VERSION
C              XLZ     : ATTENUATION
C              GCDFTZ  : MINIMUM DISTANCE FOR THE FTZ PROGRAM
C              XLUFP   :
C              FLUX    : 10.7 cm RADIO NOISE FLUX FOR A GIVEN MONTH
C              CY12    : NOON SOLAR ZENITH ANGLE (DEGS)AT EACH CONTROL P
C              CYRAD   : NOON SOLAR ZENITH(CY12 in radians)
C              DMX0    : Dmax (rec. 533)
C              DMXA    : VALUES OF Dmax AT EACH UT HOUR
C  /FILES/ INPUT AND OUTPUT NUMBERS
C              LU2     :  2   IONOSPHERIC LONG TERM DATA BASE
C              LU5     :  5   INPUT CIRCUIT DATA (FOR GRAPHICS 1 )
C              LU6     :  6   OUPUT PRINTER
C              LU7     :  7   INPUT CIRCUIT DATA (FOR GRAPHICS 2 )
C              LU15    :  15
C              LU61    :  61  INTERNAL INPUT/OUPUT FILE
C              LUI     : LU5
C              LUO     : LU6
C  /FRQ/ FREQUENCY COMPLEMENT (DBU252)
C              FREL(14) : FREQUENCY VALUES
C              FREQ     : FREQUENCY
C              FXEMAX   : MAX. VALUE OF FOE
C  /GEOG/ GEOGRAPHIC VARIABLES AT SAMPLE AREA (GEOM,TIMVAR,MAGFIT,LUFFY)
C              ABIY(5)   : ABSORPTION INDEX
C              CLAT(5)   : GEOGRAPHIC LATITUDE OF THE REFLECTION POINT
C              CLONG(5)  : GEOGRAPHIC LATITUDE OF THE REFLECTION POINT
C              CLCK(5)   : LOCAL TIME AT THE REFLECTION POINT
C              EPSPAT(5) : DIELECTRIC INDEX
C              F2M3(5)   : M3000F3 AT THE REFLECTION POINT
C              FI(2,5)   : FOE AND FOF2 AT THE REFLECTION POINT
C              GLAT(5)   : GEOMAGNETIC LATITUDE OF THE REFLECTION POINT
C              GMDIP(5)  : GEOMAGNETIC DIP AT THE REFECTION POINT
C              GYZ100(5) : GYROFREQUENCY(height=100km)AT THE REFLECTION POINT
C              GYR100    : mean GYROFREQUENCY at 100km over control points
C              HPF2(5)   : VIRTUEL HEIGHT OF THE FOF2 LAYER
C              RD(5)     : CENTER ARC
C              SIGPAT(5) : SIGMA CONSTANT
C /ION/ DESCRIPTIVE AND CONTROL VARIABLES
C              IRLAT     : HEMISPHERE (N OR S) OF THE RECEIVER
C              IRLONG    : HEMISPHERE (W OR E) OF THE RECEIVER
C              ITLAT     : HEMISPHERE (N OR S) OF THE TRANSMITTER
C              ITLONG    : HEMISPHERE (W OR E) OF THE TRANSMITTER
C              IRCVR(5)  : NAME OF RECEPTION STATION
C              ITRANS(5) : NAME OF TRANSMISSION STATION
C              IT        : U.T. OF CALCULATION S
C              ITRUN     : RUN OPTION INDICATOR
C              KM        : NO. OF SAMPLE AREAS (1,3, OR 5)
C              METHOD    : VARIABLE DEFINING OUTPUT METHOD
C              NPSL      : =0,1 FOR SHORT,LONG GREAT CIRCLE PATH CALC.
C              NPAGO     : BEGINNING PAGE NUMBER
C              NYEAR     : YEAR
C  /IPAR/ 24 HOURS OF IONOSPHERIC DATA
C              XF2(3,24)  : FOF2
C              XM3(3,24)  : M3000F2
C               XE(5,24)  : FOE
C            CY24H(5,24)  : SOLAR ZENITH ANGLE
C              KF         : Number of F2 mode control point locations
C  /MODES/ RAY MODES, LOSSES ETC..FOR PATH RANGE
C              DELMOD(9): ELEVATION ANGLES
C              UTMOD(9) : NUMBER OF HOPS ON E OR F LAYERS
C              ABPS(9)    : IONOSPHERIC ABSORBTION (E AND F MODE)
C              FLDST(9)   : FIELD STRENGTH (E AND F MODE)
C              FSLOS(9)   : TRANSMISSION ABSORBTION REFERENCE (E AND F)
C              GRLOS(9)   : GROUND REFLECTION LOSS
C              TLOSS(9)   : SUM OF ABSORBTION (E AND F MODE)
C  /MUFS/ MUF VALUES
C              EMUF(24,3)   : E/F1 MUF VALUE IN FUNCTION OF HOUR
C              F2MUF(24,6)  : F2 MUF VALUE IN FUNCTION OF HOUR
C              ALLMUF(24) : MUF OF THE CIRCUIT
C              FOT(24)    : 0.85*F2MUF(24,6)
C              HPF(24)    : 1.15*F2MUF(24,6)
C              ZLUF(24)   : LUF VALUE AS FUNCTION OF HOUR
C  /NAMEX/ INPUT/OUTPUT CONTROL PARAMETERS
C              NAMES(20)  : ARRAY OF LITERAL INDENTIFIERS (I.E. OUTPUT)
C              ISSN       : SUNSPOT NUMBER R12
C              IRED       :
C              LINES      : LINE COUNT
C              LPAGES     : PAGE COUNT
C              MAPIN      : =-1 IF DATA NOT READ, ELSE =1 (not used now GH)
C              KRUN       : NO LONGER USED
C  /SOL/  MONTHLY MEDIAN VALUES OF SOLAR DECL., EQUATION-OF-TIME etc
C              DECL12(12) : MONTHLY VALUES OF SOLAR DECL.
C              EQT12(12)  : EQUAT. OF TIME
C              DECL,EQT   : VALUES OF ABOVE FOR GIVEN MONTH
C              MONTH      : MONTH NO. (JAN=1 etc)
C              IMON(12)   : MONTHS ('JAN', 'FEB' etc)
C  /ONE/ NUMERICAL MAP COEEFICIENTS (REDMAP)
C              IFA(10)      : INDICES FOF2
C              IMA(10)      : INDICES M3000F2
C              F2COF(13,76) : MEDIAN VALUES OF FOF2
C              FM3COF(9,49) : MEDIAN VALUES OF M3000F2
C              SYS(9,16,6)  : MEDIAN AND DECILE DIFFERENCES FOR THE
C              DISTRIBUTION OF TRANSMISSION LOSS
C  /TWO/ COEFFS OF NOISE VAR,.FREQ. DEP.,REP 322-3 1 MHZ ATM NOISE
C  /NOISE/ VALUES OF ATM.,MAN-MADE AND GALALACTIC NOISE ETC
C  /NSTATS/ VALUES OF UPPER,LOWER DECILES OF ATM,MAN-MADE,GALACTIC NOISE
C  /FADE/ REQ'D % TIME FOR S/N,FBX AND FADING STATISTICS (REP 266)
C  /HOG/
C              IANT  : ANTENNA TYPE
C              BANT  : ANTENNA BEARING
C              CAL   : ANTENNA CALIBRATION
C  /XG/
C              FSCHR(5,24)    :
C              FBTRM(5,24)    :
C              EMUFY(5,24)    :
C              ELUFY(24)      :
C              UF(24)         :
C  /XK/                       : FIELD STRENGTH AND SIGNAL ON NOISE TABLE
C              TAB(24,12)     : FIELD STRENGTH TABLE (FTZ)
C              TABSN(24,12)   : SIGNAL ON NOISE RATIO (FTZ)
C              XLY            : ADDITIONAL LOSS TERM (LONG. DIST)
C  /XM/
C              FTZLNG(50)     :
C              FTZLAT(50)     :
C              IMIT(5)        :
C              GYRO(5)        :
C              GYRZ           :
C********************************************************************
      BLOCK DATA
C.....BLOCK DATA SUBPROGRAM USED TO ENTER DATA INTO LABELED COMMON
C.....PRIOR TO PROGRAM EXECUTION
C ----------------------------------------------------------------------
      LOGICAL LHOP
      CHARACTER*4 NAMES,APW
      CHARACTER*4 NYEAR,IMON,XSN
      CHARACTER*40 VERSN
C.....CONSTANTS,SET BELOW.
      COMMON /CON/D2R, DCL, GAMA, PI, PI2, PIO2, R2D, RZ, VOFL
C GENERAL GEOGRAPHIC VARIABLES, SEE SUBROUTINE GEOM
      COMMON /DON/AMIN,AMIND,BTR,BTRD,BRTD,GCD,GCDKM,PWR,XPW,APW
     A ,RLAT,RLATD,RLONG,RLONGD,SSN,TLAT,TLATD,TLONG,TLONGD,PLAT,PLONG
     B ,PGLAT,ACAV,ASM,FEAV,GMT,VERSN,XLZ,GCDFTZ,GCDEND,XINTS,XINTL
     C ,FLUX,CY12(5),DMXA(24),DMX0,CYRAD(5)
      LOGICAL YNOISE
      COMMON /TNOISE/BDWTH,JBW,JRSN,LUF,MAN,RLUF,RSN,XSN(2),YNOISE
C INPUT AND OUTPUT FILE NUMBERS
      COMMON / FILES / LUI,LUO,LU2,LU5,LU6,LU8,LU16,LU61,LU7,LU15
C FREQUENCY COMPLEMENT
      COMMON /FRQ/ FREL(12),FREL5(11,7),FW5(11,7),MAXF,MF,KOF,FREQ
     A, JKF,FXEMAX
C GEOGRAPHIC VARIABLES AT SAMPLE AREAS,SEE GEOM,TIMVAR,MAGFIT AND LUFFY.
      COMMON/GEOG/ABIY(5),CLAT(5),CLONG(5),CLCK(5),EPSPAT(5),F2M3(5)
c>>(b)WP-6A SEPT. 93 MODS add 2 lines REMOVE 1 LINE
     A,FI(3,5),GLAT(5),GMDIP(5),GYZ100(5),GYR100,GYZ300(5),HPF2(5),RD(5)
     B,SIGPAT(5),CYCEN(5)
CX   A,FI(3,5),GLAT(5),GMDIP(5),GYZ(5),HPF2(5),RD(5),SIGPAT(5),CYCEN(5)
c>>(b)WP-6A SEPT. 93 MODS end of change
      CHARACTER*4 IRLAT,IRLONG,ITLAT,ITLONG,ITRANS,IRCVR
      COMMON /ION/ IRLAT,IRLONG,ITLAT,ITLONG,IRCVR(5),ITRANS(5),IT,ITRUN
     A,IT1,IT2,ITSTEP,KM,IA,METHOD,ICON,NPSL,NYEAR,NPAGO,ICGM
      COMMON /D2HOP/ LHOP,NK,KM1,KM2,KM3
C 24 HOURS OF IONOSPHERIC DATA
      COMMON /IPAR/ XF2(3,24),XM3(3,24),XE(5,24),CY24H(5,24),KF
C RAY MODES FOR DISTANCE GHOP,SEE SUBROUTINE CURMUF
      COMMON/MODES/ DELMOD(9),UTMOD(9),ABPS(9),FLDST(9),FSLOS(9)
     1,GRLOS(9),TLOSS(9),XLOSS(9),DELMD1(9),UTMD1(9),KANGLE(12)
     2,DBLOS(12),DBU(12),MODE(12),NHP(12),KANGLA(24,12)
     3,MODEA(24,12),KANGL4(4,12),KDBU4(4,12),DBU4(4,12),MODE4(4,12)
     4,NHP4(4,12),KODEA(24,12)
       character*4 MODE,MODEA,MODE4
C     MUF VALUES
      COMMON/MUFS/ EMUF(24,3),F2MUF(24,6),ALLMUF(24),EFMUF(24),FOT(24)
     A ,FOT1(24),XLUF(24),ZLUF(24),OPMUF(24),OPMUF1(24),FU(24),FL(24)
     B, KFN,LUFC,NLOOP,ACT1,DXL,XMODE,FX,PR
C INPUT/OUTPUT CONTROL PARAMETERS
      COMMON/NAMEX/NAMES(20),ISSN,IRED,LINES,LPAGES,MAPIN,KRUN
      COMMON /SOL/ DECL12(12),EQT12(12),DECL,EQT,MONTH,IMON(12)
C LOSSES FOR MODES.  SUBROUTINES DBU252,FTZ
C NUMERICAL MAP COEFICENTS, SEE REDMAP.
      COMMON/ONE/IFA(10),IMA(10),F2COF(13,76),FM3COF(9,49),SYS(9,16,6)
      COMMON /TWO /DUD(5,12,5),FAM(14,12),FAKP(29,16,6),FAKABP(2,6)
      COMMON / HOG / IANTT, BANTT, IANTR, BANTR
C
C COMMONS FOR FTZ
C
      COMMON /XG/ FSCHR(2,24),FBTRM(2,24),YLUF(24),UF(24)
      COMMON /XK/ YTAB(24,12), YSPWR(24,12), XLY
C
C SET PREDEFINED CONSTANTS.
C
C     CONSTANTS
      DATA LHOP /.FALSE./
      DATA RZ/6371./, PI/3.1415926/, VOFL/299.79246/, DCL/1.28/
      DATA GAMA/0.57721566/,PI2/6.283185307/,PIO2/1.570796326/
      DATA D2R/.01745329251/, R2D/57.295779513/
      DATA AMIND/3./,AMIN/0.05236/,PWR/1./
      DATA LU2/12/
      DATA LU5/5/,LU6/6/,LU8/8/,LU16/16/,LU61/10/,LU7/7/,LU15/15/
      DATA IMON /'JAN ','FEB ','MAR ','APR ','MAY ','JUN '
     A,'JUL ','AUG ','SEP ', 'OCT ','NOV ','DEC '/
C.....FIRST FOUR CHARACTERS OF "NAME IDENTIFIER" USED TO IDENTIFY INPUT
      DATA NAMES/'OUTP', 'MSUN', 'TIME', 'TRAN', 'RECV', 'SYST',
     A 'NOIS', 'FREQ', 'EXEC', 'QUIT', 'METH', 'MONT', 'SUNS',
     B 'LABE', 'CIRC', 'ANTE', 'AREA', 'COEF', 'FSLI', 'DIGI'/
C.....SET,FOR 'SHORT OUTPUT' ,INDICATOR 'XSN' * IF S/N .GT. REQ S/N
C.....OTHERWISE FILL INDICATOR WITH BLANKS
      DATA XSN/'  * ','    '/
C.....STORE MONTHLY MEAN VALUES OF SOLAR DECLINATION(DEGS)
C.....AND EQUATION-OF-TIME
      DATA DECL12/-21.14,-12.70,-2.07,9.82,18.91,23.32,21.50,14.00,2.96
     1,           -8.58,-18.59,-23.27/
      DATA EQT12/-2.34,-3.54,-2.24,-0.04,0.92,-0.10,-1.48,-1.12,1.20
     1,           3.54, 3.84, 1.21/
      DATA METHOD/1/
      DATA IT1/1/, IT2/24/, ITSTEP/1/
      DATA IRED/1/
      DATA FREL/4.0,6.9,7.2,9.6,11.8,13.5,15.3,17.8,21.6,25.8,2*0.0/
      DATA ITRUN/1/,LPAGES/0/,MAXF/10/,MF/11/
      DATA MONTH/3/,NYEAR/' '/,SSN/16./,ITRANS/' LON','DON ',
     1     3*'    '/,IRCVR/' BER','LIN ',3*'    '/
      DATA NPAGO/0/,KRUN/0/,KM/1/
      DATA  IANTT/0/, BANTT/0.0/, IANTR/0/, BANTR/0.0/
      DATA LUF/50/,RLUF/0.50/,MAN/0/,JBW/1/,BDWTH/1.0/
     1,JRSN/48/,RSN/48.0/
C     PRESET TO LONDON TO BERLIN SO THAT A CIRCUIT CARD IS NOT NECESSARY
      DATA TLATD/51.50/, ITLAT/1HN/, TLONGD/0.17/, ITLONG/1HW/,
     A RLATD/52.50/, IRLAT/1HN/, RLONGD/13.40/, IRLONG/1HE/, NPSL/0/
      DATA TLAT/0.89884/,TLONG/0.00297/,RLAT/0.91630/
      DATA RLONG/-0.23387/,GCDKM/934.2/,GCD/0.14663/,BTR/1.3587/
      DATA BTRD/77.85/, BRTD/268.56/, ISSN/0/, CYCEN/5*0./, IT/1/
      DATA RD/0.07332,.0,.0,.0,.0/,GLAT/0.93521,.0,.0,.0,.0/
      DATA CLAT/0.91095,.0,.0,.0,.0/,CLONG/-0.11412,.0,.0,.0,.0/
      DATA SIGPAT/.001,.001,.001,.001,.001/,EPSPAT/4.,4.,4.,4.,4./
      DATA GYZ100/1.27,.0,.0,.0,.0/,GMDIP/0.9832,.0,.0,.0,.0/
      DATA GYR100/1.28/,GYZ300/1.28,0.,0.,0.,0./
C.....CORRECTION VALUE LZ (VARIABLE NAME XLZ)=9.8 DB SHORT PATHS
C.....CORRECTION VALUE LY (VARIABLE NAME XLY)=-3.7 DB LONG PATHS
      DATA XLZ,XLY/9.8,-3.7/
C.....TRANSITION DISTANCE FROM ITS TO FTZ =7000KM (INTERP. 7-9000 KM)
      DATA GCDFTZ/7000./
      DATA LINES/60/
C
C     PROGRAM VERSION NUMBER  (FORTRAN '77 COMPATIBLE)
C
C ----------------------------------------------------------------------
C
C.....VERSION FOR REC. 533  SG6 MAY 1992
      DATA VERSN /'REC533 Version 00.0000         '/
C.....VERSION FOR REC. 533  SG6 MAY 1992
ccc   DATA VERSN /'REC533 ITS VER-2.20  09.Jan.95     '/
c          to allow for URSI 88 foF2 coefficients
ccc   DATA VERSN /' REC533 ITS VER-2.10   03.Nov.94     '/
C
C ----------------------------------------------------------------------
      END
