c###class.for
      SUBROUTINE CLASS(I1,I2,FLDST,UTMOD,NMODES,DELMOD,TLOSS)
C.....VERSION 16.05.88
      REAL FLDST(9),UTMOD(9),DELMOD(9),TLOSS(9)
      character *4 NMODES(9),TEMPTX
      INTEGER I1,I2
      LMODE=I2-1
  10  CONTINUE
      LMODE1=0
      DO 2 KMODE=I1,LMODE
      KMODE1=KMODE
      KMODE2=KMODE+1
      IF(FLDST(KMODE1).LT.FLDST(KMODE2)) THEN
      TEMPTX=NMODES(KMODE2)
      UTEMP=UTMOD(KMODE2)
      TEMP=FLDST(KMODE2)
      TDEL=DELMOD(KMODE2)
      TTLOS=TLOSS(KMODE2)
      NMODES(KMODE2)=NMODES(KMODE1)
      NMODES(KMODE1)=TEMPTX
      UTMOD(KMODE2)=UTMOD(KMODE1)
      UTMOD(KMODE1)=UTEMP
      DELMOD(KMODE2)=DELMOD(KMODE1)
      DELMOD(KMODE1)=TDEL
      TLOSS(KMODE2)=TLOSS(KMODE1)
      TLOSS(KMODE1)=TTLOS
      FLDST(KMODE2)=FLDST(KMODE1)
      FLDST(KMODE1)=TEMP
      LMODE1=1
      ENDIF
    2 CONTINUE
      LMODE=LMODE-1
      IF(LMODE.GE.I1.AND.LMODE1.EQ.1) GO TO 10
      RETURN
      END
