      SUBROUTINE CLASS1(I1,I2,SIGPWR)
C.....VERSION 16.01.93 SORT SIGNAL POWER
      REAL SIGPWR(9)
      INTEGER I1,I2
      LMODE=I2-1
  10  CONTINUE
      LMODE1=0
      DO 2 KMODE=I1,LMODE
      KMODE1=KMODE
      KMODE2=KMODE+1
      IF(SIGPWR(KMODE1).LT.SIGPWR(KMODE2)) THEN
       TEMP=SIGPWR(KMODE2)
       SIGPWR(KMODE2)=SIGPWR(KMODE1)
       SIGPWR(KMODE1)=TEMP
       LMODE1=1
      ENDIF
    2 CONTINUE
      LMODE=LMODE-1
      IF(LMODE.GE.I1.AND.LMODE1.EQ.1) GO TO 10
      RETURN
      END
