c###cords.for
      SUBROUTINE CORDS(XU,R)
C.....VERSION 14.APR.88
C.....FINDS COMPASS POINTING(N,S,E,W,n..etc) IN ARRAY BUF.
C ..... THE RESULT IS RETURNED IN RESERVED LOCATION BUF(80).
C ..... INPUT FORMATS: XCCC.dd,XCCC,CCC.ddX,CCCX and CCCXdd
C ..... WHERE CCC=INTEGER COMPONENT,dd=DECIMAL DEGREES OR MINUTES
C ..... CO-ORDINATES ARE RETURNED AS REAL VARIABLE 'R'
 
      LOGICAL U,L
      CHARACTER*1 BUF(80),BUF7(7),CP(10)
      CHARACTER*7 WUF
      COMMON/PARAM/BUF,K1,K2,LK1,LK2
      EQUIVALENCE (WUF,BUF7(1))
      DATA CP/'N','S','E','W','n','s','e','w',' ','.'/
      IF(XU.EQ.90.) NU=1
      IF(XU.EQ.360.) NU=3
      K3=0
      DO 100 I=K1,K2
      IK=I
      K3=K3+1
      U=BUF(I).EQ.CP(NU).OR.BUF(I).EQ.CP(NU+1)
      NL=NU+4
      L=BUF(I).EQ.CP(NL).OR.BUF(I).EQ.CP(NL+1)
C..... IF 'U' OR 'L' .TRUE. THEN CHAR. BUF(I) IS A COMPASS
C..... POINTING, STORE IN BUF(80) AND RESET BUF(I) TO BLANK
      IF(U.OR.L) THEN
      BUF(80)=BUF(I)
      IMINUS=IK-1
      IPLUS=IK+1
C.... TEST IF CO-ORD'S IN IFRB LIST FORM (CCCXdd)
       IF(BUF(IMINUS).NE.CP(9).AND.BUF(IPLUS).NE.CP(9)) THEN
       BUF(I)=CP(10)
       ELSE
       BUF(I)=CP(9)
       END IF
      ELSE
      CONTINUE
      END IF
      BUF7(K3)=BUF(I)
  100 CONTINUE
C..... READ REAL VARIABLE 'R'
      READ(WUF,300) R
  300 FORMAT(F7.0)
      RETURN
      END
