      SUBROUTINE FTZ
C----------------------------------------------------------------------
C     Version 02.June.95
C----------------------------------------------------------------------
C.....NOTE: ALL 24 HOURLY VALUES OF FOF2 AND M(3000)F2 HAVE TO
C.....      BE CALCULATED BEFORE CALL TO FTZ
C.....THIS IS TO ADD THE FTZ CODE TO REC533-0
C.....IRL     1=SHORT GREAT CIRCLE PATH  ,NPSL
C.....        2=LONG GREAT CIRCLE PATH
      LOGICAL YNOISE
      INTEGER*4 PERCENT
C.....ARRAYS TGAINF,RGAINF hold values of max. antenna gain 0-8 degrees
C.....at transmitter and receiver
      REAL ELUFY(24),TGAINF(12),RGAINF(12)
      REAL RD(30),BTR(2),TBC(12,6),FTZLNG(30),FTZLAT(30)
      CHARACTER*4 NAMES,APW
      CHARACTER*40 VERSN
      common /chours/ nhours,ihours(24)
      COMMON/CON/ D2R,DCL,GAMA,PI,PID,PI2,R2D,RO,VOFL
      COMMON /TNOISE/BDWTH,JBW,JRSN,LUF,MAN,RLUF,RSN,XSN(2),YNOISE
      COMMON /DON/AMIN,AMIND,ZTR,BTRD,BRTD,GCD,GCDKM,PWR,XPW,APW
     A ,RLAT,RLATD,RLONG,RLONGD,SSN,TLAT,TLATD,TLONG,TLONGD,PLAT,PLONG
     B ,PGLAT,ACAV,ASM,FEAV,GMT,VERSN,XLZ,GCDFTZ,GCDEND,XINTS,XINTL
     C ,FLUX,CY12(5),DMXA(24),DMX0,CYRAD(5)
      COMMON/NAMEX/NAMES(20),ISSN,IRED,LINES,LPAGES,MAPIN,KRUN
      COMMON /IPAR/ XF2(3,24),XM3(3,24),XE(5,24),CY24H(5,24),KF
      COMMON / FILES / LUI,LUO,LU2,LU5,LU6,LU8,LU16,LU61,LU7,LU15
      COMMON /FRQ/ FREL(12),FREL5(11,7),FW5(11,7),MAXF,MF,KOF,FREQ
     A, JKF,FXEMAX
      COMMON /FSTAB/ ZTAB(24,12),ZSPWR(24,12)
      COMMON /GEOG/ ABIY(5),CLAT(5),CLONG(5),CLCK(5),EPSPAT(5)
c>>(b)WP-6A SEPT. 93 MODS add 2 lines REMOVE 2 LINES
     A,F2M3(5),FI(3,5),GLAT(5),GMDIP(5),GYZ100(5),GYR100,GYZ300(5)
     B,HPF2(5),RX(5),SIGPAT(5),CYCEN(5)
CX     1,F2M3(5),FI(3,5),GLAT(5),GMDIP(5),GYZ(5),HPF2(5),RX(5)
CX     2,SIGPAT(5),CYCEN(5)
c>>(b)WP-6A SEPT. 93 MODS end of change
      character*4 IRLAT,IRLONG,ITLAT,ITLONG,IRCVR,ITRANS
      COMMON /ION/ IRLAT,IRLONG,ITLAT,ITLONG,IRCVR(5),ITRANS(5),IT,ITRUN
     A,IT1,IT2,ITSTEP,KM,IA,METHOD,ICON,NPSL,NYEAR,NPAGO,ICGM
C.WP3L.RG4  June 95 add 'SFA' to COMMON /NOISE/
      COMMON /NOISE/ ATMO,GNOS,XNOISE,SFA,ATNU,ATNY,CC,TM,KJ,JK
      COMMON /NSTATS/ DU,DL,DUA,DLA,DUM,DLM,DUG,DLG
      COMMON/MUFS/ EMUF(24,3),F2MUF(24,6),ALLMUF(24),EFMUF(24),FOT(24)
     A ,FOT1(24),XLUF(24),ZLUF(24),OPMUF(24),OPMUF1(24),FU(24),FL(24)
     B, KFN,LUFC,NLOOP,ACT1,DXL,XMODE,FX,PR
C RAY MODES FOR DISTANCE GHOP,SEE SUBROUTINE CURMUF
      COMMON/MODES/ DELMOD(9),UTMOD(9),ABPS(9),FLDST(9),FSLOS(9)
     1,GRLOS(9),TLOSS(9),XLOSS(9),DELMD1(9),UTMD1(9),KANGLE(12)
     2,DBLOS(12),DBU(12),MODE(12),NHP(12),KANGLA(24,12)
     3,MODEA(24,12),KANGL4(4,12),KDBU4(4,12),DBU4(4,12),MODE4(4,12)
     4,NHP4(4,12),KODEA(24,12)
       character*4 MODE,MODEA,MODE4
      COMMON /SOL/ SUN(12),EQT12(12),DECL,EQT,MONTH,IMON(12)
C.WP3L.RG4  Jun mod 1 line
      COMMON /FADE/ PERCENT,FRACX,FSX,FBX,DUSN,DLSN,SDU,SDL,SHU,SHL
      COMMON /XK/ YTAB(24,12),YSPWR(24,12),XLY
      COMMON /XG/ FSCHR(2,24),FBTRM(2,24),YLUF(24),UF(24)
      COMMON / HOG / IANTT, BANTT, IANTR, BANTR
      DATA TBC/1.10,1.05,8*1.00,1.05,1.10,1.05,1.02,8*1.00,1.02,1.05,
     11.05,1.02,1.00,1.00,1.02,1.05,1.05,1.02,1.00,1.00,1.02,1.05,16*
     21.00,1.02,1.05,1.05,1.02,8*1.00,1.05,1.10,1.10,1.05,4*1.00/
      DATA TEN/10.0/
      SUM2(A1,A2)=SQRT(A1*A1+A2*A2)
      SUM3(A1,A2,A3)=SQRT(A1*A1+A2*A2+A3*A3)
C.....FORMULA FOR CALC. OF SIGNAL POWER (Rec. 533 eq.35)
      SPWF(FS,RGAIN,OPFREQ)=FS+RGAIN-20.0*ALOG10(OPFREQ)-107.2
      data FLOW,FHIGH/2.,30./
      X10=TEN*ALOG10(BDWTH)
      IRL=1
      IF(NPSL.GT.0 ) IRL=2
      SSP=SUN(MONTH)*D2R
C.....COMPUTE GREAT CIRCLE DISTANCE AND MUF CONTROL POINTS
      XX1=TLAT
      XX2=RLAT
C.....NOTE SWITCH IN EAST WEST
      YY1=-TLONG
      YY2=-RLONG
C.....NEED DISTANCE BEFORE CALL
       GCDK=GCD
      IF(IRL.EQ.2) GCDK=2.0*PI-GCD
C.....COMPUTE FTZ LUF CONSTANTS
      HOP=AINT(GCDKM/3000.)+1.0001
      K6=2.0*HOP+0.0001
      ARCHOP=GCD/HOP
      AR2=ARCHOP/2.
      PHIF=ATAN(RO*SIN(AR2)/(RO+300.0-RO*COS(AR2)))
      DP2N= RO  *SIN(AR2)/SIN(PHIF)
C.....NOTE ALSO THAT THE HOP LENGTH IS 3000 KM AND THE VIRTUAL HEIGHT
C.....     IS 300, SO THE TAKEOFF ANGLE IS 4.2 DEGREES
      GCDKO=DP2N*HOP*2.
      DELTA=PI-PHIF-AR2
      PHID=ASIN(RO*SIN(DELTA)/(RO+90.) )
C.....B IS THE FTZ LUF FACTOR
      B=5.3/SQRT (COS (PHID)*ALOG(9.5E6/GCDKO))
C.....COMPUTES THE DISTANCES TO THE PENETRATION POINTS
      DP=PI-DELTA-PHID
      DN2=2.*DP
      DN4=ARCHOP-DN2
      RD(1)=DP
      KG=K6-1
C.....
      DO 188  I=1,KG,2
      RD(I+1)=RD(I)+DN4
188   RD(I+2)=RD(I+1)+DN2
C.....DFK IS THE INFLUENCE FACTOR OF SOLAR ACTIVITY
      DFK=SQRT(1.0+0.009*SSN)
C.....FLUNA IS THE NIGHT FTZ LUF
      FLUNA=SQRT(GCDKM/3000.0)
      FLUNA2=FLUNA*2.0
C.....COMPUTE THE SEASONAL FTZ LUF FACTOR DEPENDENT ON THE GEOGRAPHICAL
C.....LATITUDE OF BOTH TERMINALS
      X1=TLAT*R2D
      X2=RLAT*R2D
      IF(X1.LE.35.) GOTO 211
      KATZ=1
      IF(X2.GT.35.) GOTO 221
      KATZ=2
      IF(X2.GE.-35.) GOTO 221
      KATZ=3
      GOTO 221
211   IF(X1.LT.-35.) GOTO 213
      KATZ=2
      IF(X2.GT.35.) GOTO 221
      KATZ=4
      IF(X2.GT.-35.) GOTO 221
      KATZ=5
      GOTO 221
213   KATZ=3
      IF(X2.GT.35.) GOTO 221
      KATZ=5
      IF(X2.GT.-35.) GOTO 221
      KATZ=6
C.....FLUF IS THE FTZ LUF FACTOR THAT CONTAINS ALL CONSTANT PARAMETERS
221   FLUF=TBC(MONTH,KATZ)*DFK*B
C.....COMPUTE THE GEOGRAPHICAL POSITIONS OF PENETRATION POINTS
      DO 270  II=1,K6
      PP=RD(II)
      CENLAT=COS (PP)*COS (PI2-XX2)+SIN(PP)*SIN(PI2-XX2)*COS(BRTD*D2R)
      CENLAT=ACOS(CENLAT)*R2D
      IF(CENLAT.GE.0.) GOTO 266
      CENLAT=-90.-CENLAT
      GOTO 268
266   CENLAT= 90.-CENLAT
268   CENLG=(COS (PP)-COS (PI2-CENLAT*D2R)*COS (PI2-XX2))/
     1SIN(PI2-CENLAT*D2R)/SIN(PI2-XX2)
      IF(ABS(CENLG).GT.1.) CENLG=SIGN(1.,CENLG)
       CENLG=ACOS(CENLG)*R2D
      IF(BRTD.GT.180..AND.PP.LT.PI.OR.BRTD.LT.180..AND.PP.GT.
     1PI) CENLG=-CENLG
      CENLG=YY2*R2D+CENLG
      IF(CENLG.GT.180.) CENLG=CENLG-360.
      IF(CENLG.LT.-180.) CENLG=CENLG+360.
      FTZLAT(II)=CENLAT
      FTZLNG(II)=CENLG
270   CONTINUE
C.....COMPUTE W,X,Y,Z FOR THE K-FACTOR
      WOW=0.1
      WNS=0.2
      XOW=1.2
      XNS=0.2
      YOW=0.6
      YNS=0.4
      GCDX=GCDK/2.
      CALL BEAR (BTR,XX1,YY1,CLAT(3),-CLONG(3),GCDX)
      BTT=BTR(2)
      IF(BTT.LE.180.) GOTO 290
      BTT=BTT-180.
290   IF(BTT.LT.90.) GOTO 292
      BTT=BTT-90.
      GOTO 294
292   BTT=90.-BTT
294   ZB=BTT/90.
      ZL=1.-ZB
      WW=WOW*ZL+WNS*ZB
      XX=XOW*ZL+XNS*ZB
      YY=YOW*ZL+YNS*ZB
C.....COMPUTE F2-MUF
      DO 322 II=1,2
      KK=II*2
      K1=KK-1
      DO 320 IT=1,24
c>>(e)WP-6A SEPT. 93 MODS add 25 lines  remove 1 line
C......CALCULATE F2(4000)MUF (array FSCHR) FROM  1.1* F2(3000)MUF
C......WHERE F2(3000)MUF IS CALC. using rec. 434 formulae
C......at the control points d0 from TX , Rx respectively (Table 1a)
       KFE=K1+1
       FOE=XE(KFE,IT)
C.......
       IF(II.EQ.1) THEN
        F22=XF2(K1,IT)
        XR2=F22/FOE
        FH2=GYZ300(2)
        CALL MUF434(F22,XR2,XM3(K1,IT),FH2,3000.0,1,2,DMXF,F232)
        FSCHR(II,IT)=F232*1.1
       ELSE
        F24=XF2(K1,IT)
        XR4=F22/FOE
        FH4=GYZ300(4)
        CALL MUF434(F24,XR4,XM3(K1,IT),FH4,3000.0,1,4,DMXF,F234)
        FSCHR(II,IT)=F234*1.1
       END IF
320   CONTINUE
CX 320   FSCHR(II,IT)=XF2(K1,IT)*XM3(K1,IT)*1.1
c>>(e)WP-6A SEPT. 93 MODS end of change
      IMIT=12.0+(CLONG(KK)*R2D)/15.0
      IF(IMIT.LT.1) IMIT=IMIT+24
      CALL KORMU(II,IMIT,XX,YY,WW)
322   CONTINUE
c>>(b) and (e)WP-6A SEPT. 93 MODS CHANGE use gyrofrequency at ht = 300 km
      GYR300=(FH2+FH4)*0.5
      K1=2
      K2=3
C.....COMPUTE FTZ LUF
      DO 334   IT=1,24
      GMT=IT
      ZT=(15.0 * GMT-180.0) * D2R
      ELUFY(IT)=0.0
      DO 332  II=1,K6
      CENLG=FTZLNG(II) * D2R
      CENLAT=FTZLAT(II) * D2R
      Z=ZT+CENLG
      XYCEN=SIN (CENLAT)*SIN (SSP)+COS (CENLAT)*COS (SSP)*COS (Z)
      IF(XYCEN.GT.0.) GOTO 330
      XYCEN=0.
      GOTO 332
330   XYCEN=SQRT (XYCEN)
332   ELUFY(IT)=ELUFY(IT)+XYCEN
c>>(b)WP-6A SEPT. 93 MODS CHANGE use gyrofrequency at ht = 300 km
      ELUFY(IT)=SQRT (ELUFY(IT))*FLUF-GYR300
      IF(ELUFY(IT).GE.FLUNA) GOTO 334
      ELUFY(IT)=FLUNA
334   CONTINUE
      XXM=CLAT(3)*R2D
      CALL WINTER(ELUFY,XXM,MONTH,FLUNA)
C.....COMPUTE DECAY TO THE NIGHT FTZ LUF
      DO 360 IT=1,24
      ILF=IT-1
      IF(ILF.GT.0) GOTO 350
      ILF=ILF+24
350   IF(ELUFY(ILF).LE.ELUFY(IT)) GOTO 360
      IF(ELUFY(IT).GT.FLUNA2) GOTO 360
      IF(ELUFY(IT).EQ.FLUNA2) GOTO 355
      IF(ELUFY(ILF).LT.FLUNA2) GOTO 360
      IF(ELUFY(ILF).EQ.FLUNA2) GOTO 358
      ILB=IT
      GOTO 362
355   ILB=IT
      GOTO 364
358   ILB=ILF
      GOTO 364
360   CONTINUE
      GOTO 378
362   ELUFY(ILB)=0.795*ELUFY(ILF)*(((FLUNA2-ELUFY(ILB))/(ELUFY(ILF)-
     1ELUFY(ILB)))*0.205+0.795)
      IF(ELUFY(ILB).LT.FLUNA) ELUFY(ILB)=FLUNA
C.....CALC. FTZ LUF AFTER DARK FOR THREE SUBSEQUENT HOURS
364   DO 376 IT=1,3
      ILF = IT+ILB
      ILG = ILF-1
      IF (ILF.EQ.25) GOTO 368
      IF (ILF.LT.25) GOTO 370
      ILG = ILG-24
368   ILF = ILF-24
370   IF (ELUFY(ILF).LT.FLUNA) GOTO 376
      ELU=ELUFY(ILG)*0.795
      ELUFY(ILF)=AMAX1(ELU,ELUFY(ILF))
      IF (ELUFY(ILF).GE.FLUNA) GOTO 376
      ELUFY(ILF) = FLUNA
376   CONTINUE
378   CONTINUE
C.....CHOSE HIGHEST MUF AND CALC. FOT,LOWER DECILE OF OP. MUF-ARRAY FOT1
      DO 400 IT=1,24
ccc      EFMUF(IT)=AMIN1(FSCHR(1,IT),FSCHR(2,IT))
      XDANI=0.0
      IF(ELUFY(IT).LT.FLUNA2) XDANI=200.0
C.....
C.....CALCULATE MAXIMUM TX ANTENNA GAIN TGAINF BETWEEN 0.0 AND 8 DEG. AT MUF
ccc      FREQ12=EFMUF(IT)
      FREQ12=ALLMUF(IT)
      FREL(12)=FREQ12
      TGAINF(12)=-30.0
ccc      IF(IANTT.GT.2) TGAINF(12)=-100.0
      DELFTZ=3.0
180   CONTINUE
      call ANTCALZ(1,FREQ12,BANTT,BTRD,DELFTZ,TGAINX)  !  at the transmitter
      TGAINF(12)=AMAX1(TGAINF(12),TGAINX)
      DELFTZ=DELFTZ+1.00
      IF(DELFTZ.LE.8.0) GO TO 180
C.....
      EIRP=PWRDB(FREQ12)+30.0+TGAINF(12)
ccc      OPMUF1(IT)=FOP(MONTH,XDANI,EIRP)*EFMUF(IT)
      OPMUF1(IT)=FOP(MONTH,XDANI,EIRP)*ALLMUF(IT)
      FOT1(IT)=OPMUF1(IT)*0.85
400   UF(IT)=AMIN1(FBTRM(1,IT),FBTRM(2,IT))
C.... COMPUTE GAP FOCUS GAIN TERM
      A=RO*ABS(SIN(GCDKM/RO))
      GAP=10.*ALOG10(GCDKM/A)
      GAP=AMIN1(GAP,15.0)
C----------------------------------------------------------------
C.....COMPUTE FIELD STRENGTH
C.....FSCHR,FBTRM,ELUFY: ARRAYS OF HOURLY MUFS,OPERATIONAL MUFS,AND LUFS
      D0=139.6-20.0*ALOG10(GCDKO)
      EXPO=2.0
C.....
      DO 578 ihr=1,nhours
      I=ihours(ihr)
      if(i.gt.24) i=i-24
c>>(b)WP-6A SEPT. 93 MODS CHANGE use gyrofrequency at ht = 300 km
      FM2=(UF(I)+GYR300)**EXPO
      FL2=(ELUFY(I)+GYR300)**EXPO
      IF(UF(I).GE.ELUFY(I)) GOTO 572
      CLM=FL2/(FM2+FL2)
      GO TO 574
572   CLM=FM2/(FM2+FL2)
574   CONTINUE
C..... CALCULATE MEAN ATMOSPHERIC NOISE POWER AT 1 MHZ AT RECEIVER
C......where 'I' is the time
      RLMT=FLOAT(I)-RLONG*R2D/15.     !  "-" because E long is "-"
      IF(RLMT.GE.24.) RLMT=RLMT-24.
      IF(RLMT.LT.0.) RLMT=RLMT+24.
      CALL ANOIS1(RLMT,RLAT,RLONG)
C     CALC. RELIABILITY LUF,SET PARAMETERS INCL. CONTROL VALUE LUFC=1
      KFN=1
      LUFC=1
      NLOOP=0
      ACT1=1.0
      DXL=1.0
      FX=2.
      FREQ=FX
ccc      QMUF=EFMUF(I)
      QMUF=ALLMUF(I)
      FREL(12)=QMUF
      QOPMUF=OPMUF1(I)
      YLUF(I)=QOPMUF
600   CONTINUE
      NLOOP=NLOOP+1
      IF(LUFC.EQ.0) THEN
C......CALC. FIELD STRENGTH AT EACH FREQ ; SET LUF =HIGHER OF CALC. VALUE
C......AND LOWEST OPERATIONAL FREQ.
       KFN=12
       yluf_last=YLUF(I)
       YLUF(I)=AMAX1(ABS(YLUF(I)),FLOW)
       if(yluf_last.lt.0.) YLUF(I)=-YLUF(I)
ccc      write( *,'('' after  600  yluf('',i2,'')='',f10.4)') i,yluf(i)
      END IF
C.....
      DO 576 J=1,KFN
      IF(LUFC.EQ.1) THEN
C......SET INITIAL FREQUENCY TO BE USED IN EVALAUATION OF LUF
       FREQ=FX
      ELSE
C......ACCESS FREQUENCY FROM INPUT COMPLEMENT FOR LOSS CALCULATIONS
       FREQ=FREL(J)
      END IF
C.....
      XMODE=3
      YTAB(I,J)=-999.
      IF(FREQ.LE.0.0) GO TO 576
C.....
C.....CALCULATE MAXIMUM ANTENNA GAINS,TGAINF and RGAINF,BETWEEN 0.0 AND 8 DEG.
C.....AT FREQUENCY FREQ FOR BOTH LUF and STRENGTH/SYSTEM PERFORMANCE CALCS
C.....SET MIN. VALUE OF -30 DB FOR REP. 1062 ANTENNAE
C.....SET MIN. VALUE OF -100 DB FOR REC. 705 ANTENNAE TO ALLOW FOR FREQ.
C.....BEING OUT OF ANTENNAE OPERATING RANGE
      TGAINF(J)=-30.0
      RGAINF(J)=-30.0
      IF(IANTT.GT.5) TGAINF(J)=-100.0
      IF(IANTR.GT.5) RGAINF(J)=-100.0
      DELFTZ=3.0
1812  CONTINUE
      CALL ANTCALZ(1,FREQ,BANTT,BTRD,DELFTZ,TGAINX)  !  at the transmitter
      CALL ANTCALZ(2,FREQ,BANTR,BRTD,DELFTZ,RGAINX)  !  at the receiver
      TGAINF(J)=AMAX1(TGAINF(J),TGAINX)
      RGAINF(J)=AMAX1(RGAINF(J),RGAINX)
      DELFTZ=DELFTZ+1.00
      IF(DELFTZ.LE.8.0) GO TO 1812
C.....
c>>(b)WP-6A SEPT. 93 MODS CHANGE use gyrofrequency at ht = 300 km
610   F9=(FREQ+GYR300)**EXPO
      FLF=FL2/F9
      FFM=F9/FM2
      YD=(D0*(1.-CLM*(FLF+FFM)))-36.4+PWRDB(FREQ)-XLY+GAP+TGAINF(J)
      YTAB(I,J)=YD
C......CALCULATE AND STORE SIGNAL POWER PRS
      PRS=SPWF(YD,RGAINF(J),FREQ)
      YSPWR(I,J)=PRS
ccc      write( *,'('' yspwr='',4f10.4)') prs,yd,rgainf(j),freq
      IF(GCDKM.GT.GCDEND) GO TO 577
C     INTERPOLATE BETWEEN RANGES GCDFTZ,GCDFTZ+2000.0 KM OTHER
C     THAN FOR RELIABILITY LUF CALC.
ccc      IF(LUFC.NE.0) GO TO 615
C.....IF F2-MODES NOT CUT OFF BY E LAYER THEN INTERPOLATE
ccc      ZTAB1=ZTAB(I,J)
ccc      YD=ZTAB1*XINTS+YD*XINTL
ccc615   continue
C.....NOISE CALC. NOT REQ'D FOR METHODS 1,4,AND 5
577   IF(LUFC.EQ.0.AND.YNOISE) GO TO 575
C.....
C.....IN INTERPOLATION ZONE NEED ONLY TO RE-CALC NOISE AT MUF
C.....AS SHORT PATH METHOD(0-7000 KM) VALUE MAY DIFFER FROM LONG PATH
      IF(LUFC.EQ.0.AND.GCDKM.LE.GCDEND.AND.J.NE.12) GO TO 579
C.WP3L.RG4  June 95 remove 11 lines, add 1
CREMC.....CALCULATE MAN MADE NOISE POWER AT FREQUENCY FREQ
CREM      IFN=MAN
CREM      CALL GENOIS1(FREQ,IFN,RLAT)
CREMC.....SFA= RSS OF NOISE FA
CREM      SFA=XTEN3(TEN,ATMO,GNOS,XNOISE)
CREM      DU=SUM3(DUA,DUM,DUG)
CREM      DL=SUM3(DLA,DLM,DLG)
CREMC.....CALL FADING TO DETERMINE S/N DEVIATIONS FOR OTHER
CREMC.....PERCENTAGES OF DAYS ON MONTH(METHODS 2,3 ONLY)
CREM      CALL FADING !! REPLACED BU SUB. FAD842
ccc      write( *,'('' freq,frel(12)='',2f10.4)') freq,frel(12)
ccc      write( *,'('' before FAD842, j,i='',2i5,f9.4)') j,i,allmuf(i)
      CALL FAD842
ccc      write( *,'('' after  FAD842'')')
C.WP3L.RG4 May 95 END
      SFA=SFA-FBX
C.... CALC S/N REC. 533 EQ. 37
      SN=PRS-SFA-X10+204.
579   CONTINUE
ccc      write( *,'('' after 579, sn='',3f9.4)') sn,prs,sfa
C.....ALWAYS CALC. RELIABITY IN TERMS OF MONTHLY MEDIAN SIGNAL
C.....AND NOISE POWERS
C.....use SNMED to calc. median PR
      SNMED=SN
      IF(METHOD.EQ.2.OR.METHOD.EQ.3) SNMED=SN-FBX
C.WP3L.RG4  June 95 add 1 line remove 1
      CALL SNPROB(SNMED,RSN,DUSN,DLSN,PR)
ccc      write( *,'('' after SNPROB(SNMED)='',5f9.4)') 
ccc     +    snmed,rsn,dusn,dlsn,pr
CREM      CALL SNPROB(SNMED,RSN,TU1,TL1,DLSN,PR)
      IF(PR.LT.0.01) PR=0.01
      IF(PR.GT.0.99) PR=0.99
      IF(LUFC.EQ.0) GO TO 575
C.....CALL SUBROUTINE RELUF TO CALCULATE RELIBILITY LUF,YLUF,AT TIME I
      CALL RELUF(YLUF(I),QOPMUF,FLOW,FHIGH)
ccc      write( *,'('' after RELUF yluf('',i2,'')='',f10.4)') i,yluf(i)
      GO TO 600
575   CONTINUE
C.....INTERPOLATE FOR SIGNAL STRENGTH,SIGNAL POWER THENCE CALC. S/N
C.....IF IN INTERPOLATION RANGE and METHOD=6  22 FEB 93
576   CONTINUE
C.....STATEMENT 576: END OF FREQUENCY LOOP
C.....
578   CONTINUE
C.....STATEMENT 578: END OF UT LOOP
C......
      RETURN
      END
