c###kormu.for
      SUBROUTINE KORMU  (II,IMIT,X,Y,W)
C     COMPUTE OPERATIONAL MUF
      COMMON /XG/ FSCHR(2,24),FBTRM(2,24),YLUF(24),UF(24)
      UFMAX=FSCHR(II,IMIT)
      UFMIN=FSCHR(II,1)
      DO 4 I=2,24
4     UFMIN=AMIN1 (UFMIN,FSCHR(II,I))
      UFQU= Y*(UFMIN/UFMAX)**2
      DO 5 I=1,24
      F=FSCHR(II,I)
      DUF=UFMAX/F
5     FBTRM(II,I)=F*(1.2+W*(F/UFMAX)+(DUF**0.333333-1.0)*X+UFQU)
      RETURN
      END
