c###monitr.for
      FUNCTION MONITR(LU,NAMES,NX,INPUT)
C.....VERSION 23 Sept 1992   GRH
C     THIS FUNCTION READS A CARD IMAGE FROM LOGICAL UNIT LU.
C     THE FIRST TEN COLUMNS CONTAIN A STRING OF 10 HOLLERITH
C     CHARACTERS CALLED THE "NAME IDENTIFIER". THE "NAME IDENTIFIER"
C     IS COMPARED WITH THE LIST OF 10-CHARACTER STRINGS STORED IN THE
C     ARRAY CALLED "NAMES". IF A MATCH IS FOUND, THE VALUE OF MONITR
C     IS SET EQUAL TO THE SUBSCRIPT OF THE MATCHING NAME IN THE LIST.
C     A MAXIMUM OF NX=16 NAMES WILL BE SEARCHED. IF NO MATCHING NAME
C     IS FOUND, THE VALUE OF MONITR WILL BE SET TO NX+1.
C     IFORM .LE. 0 IF THE INPUT FILE IS BINARY, OTHERWISE IT IS BCD
C**********************************************************************
      CHARACTER*4 NAMES(*)
      CHARACTER*85 INPUT
C.....READ ONE CARD WITH THE "NAME IDENTIFIER" IN COLUMNS 1-10.
      READ(LU,1) INPUT
 1    FORMAT(A)
      DO 100 I=1, NX
      IF(INPUT(1:4).EQ.NAMES(I)) GO TO 105
 100  CONTINUE
C-- - - - - THERE WAS NO MATCHING NAME IN THE LIST OF NAMES.
      I=NX+1
C-- - - - - A MATCHING NAME WAS FOUND.
 105  MONITR=I
      RETURN
      END
