c###noisy.for
      SUBROUTINE NOISY (KJ, XLA, CEG, ANOS)
CR....A ROUTINE TO USE THE TIMEBLOCK (KJ), THE LAT (XLA), THE LONG
CR....(CEG), AND THE IONOSPHERIC COEFFICIENTS (FAKP AND FAKAB) TO
CR....DETERMINE THE ATMOSPHERIC NOISE (ANOS).
C.....NOISY IS A GENERAL PURPOSE ROUTINE USED TO EVALUATE A FOURIER
C.....SERIES IN TWO VARIABLES.
C.....KJ --- NUMBER OF FOURIER COEFFICIENT ARRAY TO BE USED
C.....XLA --- GEOGRAPHIC LATITUDE, DEGREES,
C.....CEG --- GEOGRAPHIC EAST LONGITUDE, DEGREES
C.....ANOS --- NOISE VALUE, MEDIAN POWER DB ABOVE KTB
C.....FAKABP --- NORMALIZING FACTORS FOR FOURIER SERIES
C.....KJ = 1 TO 6 IS ATMOSPHERIC NOISE
C.....
C.....* NOTE - XLA, CEG, ANOS, FAKABP ARE NOT ALWAYS AS PREVIOUSLY
C.....         DEFINED
C.....FOURIER VARIABLES AND ATMOSPHERIC RADIO NOISE
C.....
      COMMON /TWO/ DUD(5,12,5),FAM(14,12),FAKP(29,16,6),FAKABP(2,6)
      DIMENSION SX (15), SY(29), ZZ (29)
      IF (KJ - 6) 105,105,100
 100  KJ=6
C.....LIMITS OF FOURIER SERIES
 105  LM = 29
      LN = 15
C.....HALF ANGLE (IN RADIANS)
 110  Q = .0087266466 * CEG
C.....LONGITUDE SINES
      DO 115 K = 1, 15
 115  SX(K)=SIN(Q*K)
 118  CONTINUE
C.....LONGITUDE SERIES
      DO 125 J = 1, LM
      R = 0.
      DO 120 K = 1, LN
 120  R = R + SX (K) * FAKP (J, K, KJ)
 125  ZZ (J) = R + FAKP (J, 16, KJ)
C.....ANGLE PLUS 90 DEGREES (IN RADIANS)
      Q = .01745329252 * (XLA + 90.)
C.....LATITUDE SERIES
      DO 140 J=1,29
 140  SY(J)=SIN(Q*J)
      R = 0.
      DO 130 K = 1, LM
 130  R = R + SY (K) * ZZ (K)
C.....FINAL FOURIER SERIES EVALUATION (NOTE LINEAR NORMALIZATION)
 135  ANOS = R + FAKABP(1,KJ)+FAKABP(2,KJ)* Q
ccc      write(61,'('' In noisy='',i5,5f10.4)') 
ccc     +      kj,anos,xla,ceg,fakabp(1,kj),fakabp(2,kj)
      RETURN
      END
