c###parion.for
      SUBROUTINE PARION
C.....THIS SUBROUTINE CALCS THE IONOSPHERIC PARAMETERS FOF2,M(3000)F2
C.....FOE AND SOLAR ZENITH ANGLE CY24H AT EACH UT
C.....VERSION 10.APRIL.92
      REAL*4 TS(80)
      CHARACTER*40 VERSN
      COMMON/GEOG/ABIY(5),CLAT(5),CLONG(5),CLCK(5),EPSPAT(5),F2M3(5)
c>>(b)WP-6A SEPT. 93 MODS add 2 lines REMOVE 1 LINE
     A,FI(3,5),GLAT(5),GMDIP(5),GYZ100(5),GYR100,GYZ300(5),HPF2(5),RD(5)
     B,SIGPAT(5),CYCEN(5)
CX   A,FI(3,5),GLAT(5),GMDIP(5),GYZ(5),HPF2(5),RD(5),SIGPAT(5),CYCEN(5)
c>>(b)WP-6A SEPT. 93 MODS end of change
      COMMON /DON/AMIN,AMIND,BTR,BTRD,BRTD,GCD,GCDKM,PWR,XPW,APW
     A ,RLAT,RLATD,RLONG,RLONGD,SSN,TLAT,TLATD,TLONG,TLONGD,PLAT,PLONG
     B ,PGLAT,ACAV,ASM,FEAV,GMT,VERSN,XLZ,GCDFTZ,GCDEND,XINTS,XINTL
     C ,FLUX,CY12(5),DMXA(24),DMX0,CYRAD(5)
      COMMON /IPAR/ XF2(3,24),XM3(3,24),XE(5,24),CY24H(5,24),KF
      character*4 IRLAT,IRLONG,ITLAT,ITLONG,IRCVR,ITRANS
      COMMON/ION/IRLAT,IRLONG,ITLAT,ITLONG,IRCVR(5),ITRANS(5),IT,ITRUN
     A,IT1,IT2,ITSTEP,KM,IA,METHOD,ICON,NPSL,NYEAR,NPAGO,ICGM
      COMMON/ONE/IFA(10),IMA(10),F2COF(13,76),FM3COF(9,49),SYS(9,16,6)
      COMMON /TWO /DUD(5,12,5),FAM(14,12),FAKP(29,16,6),FAKABP(2,6)
      DATA DIST,IC/ 3400.,0/
      IA=1
      KF=3
      IF(KM .GT. 3) GO TO 100
      KF=1
      IF(KM .GT. 1) GO TO 100
      IA=0
 100  CONTINUE
C.....SPATIAL COMPONENT(LAT,LONG)
      DO 110 II=1,KF
      INDX=(II-1)*26+1
      I3A=II+IA
      INDX1=INDX+13
      CALL EVLGOG(IFA,F2COF,GMDIP(I3A),CLAT(I3A),CLONG(I3A),TS(INDX))
      CALL EVLGOG(IMA,FM3COF,GMDIP(I3A),CLAT(I3A),CLONG(I3A),TS(INDX1))
  110 CONTINUE
C.....U.T. COMPONENT
      FKF=FLOAT(KF)
      DO 120 JT=1,24
      GMT=JT
      CALL TIMVAR
      CALL MUGFOE
C.....STORE DAILY VALUES OF foE,SOLAR ZENITH ANGLE AT EACH CONTROL PT.
      DO 115 II=1,KM
      XE(II,JT)=FI(1,II)
      CY24H(II,JT)=CYCEN(II)
  115 CONTINUE
      DMXS=0.0
C.....
      DO 121 II=1,KF
      INDX=(II-1)*26+1
      CALL EVLTIM(IFA,TS(INDX),GMT,XF2(II,JT))
      CALL EVLTIM(IMA,TS(INDX+13),GMT,XM3(II,JT))
      FOF2=XF2(II,JT)
c>>(e)WP-6A SEPT. 93 MODS add 6 lines remove 1
      IF(KF.EQ.1) THEN
       KFE=1
      ELSE
       KFE=II+1
      END IF
      FOE=XE(KFE,JT)
CX    FOE=XE(II,JT)
      XR=FOF2/FOE
C.....CALL MUF434 TO CALC. ONLY VALUES OF Dmax
c>>(b)WP-6A SEPT. 93 MODS CHANGE 'GYZ' to 'GYZ300'
      CALL MUF434(FOF2,XR,XM3(II,JT),GYZ300(II),DIST,IC,KF,DMXF,F2DMUF)
      DMXS=DMXS+DMXF
  121 CONTINUE
C.....
C.....CALC. MEAN Dmax for each UT
      DMXA(JT)=DMXS/FKF
c>>(e)WP-6A SEPT. 93 MODS ad 3 lines
C.....set max value of Dmax to 7000 km as)
C.....(two control pts. are req'd for D > 7000 km procedure)
      DMXA(JT)=AMIN1(DMXA(JT),7000.0)
  120 CONTINUE
      RETURN
      END
c---------------------------------------------------------------
