      SUBROUTINE RELUF(XLUF1,QOPMUF,FLOW,FHIGH)
C -------------------------------------------------------------
C        SUBROUTINE RELUF:
C          VERSION 30.MARCH.93
C          CALCULATES LUF,THE LOWEST FREQUENCY AT WHICH A REQUIRED
C          RELIABILITY IS ACHEIVED.
C          RELIABILITY=PROBABILITY OF ACHIEVING A REQURED S/N RATIO
C          QOPMUF=OPERATIONAL MUF
C          CALC. LUF FIRST AT EACH UT TIME(LUFC=1),STORE AS XLUF1
C..........LOWER LIMIT FOR LUF SET TO FLOW, LOWEST OPERATIONAL
C..........FREQUENCY OF CIRCUIT (depends on antenna performance)
C -------------------------------------------------------------
      CHARACTER*40 VERSN
      COMMON /DON/AMIN,AMIND,BTR,BTRD,BRTD,GCD,GCDKM,PWR,XPW,APW
     A ,RLAT,RLATD,RLONG,RLONGD,SSN,TLAT,TLATD,TLONG,TLONGD,PLAT,PLONG
     B ,PGLAT,ACAV,ASM,FEAV,GMT,VERSN,XLZ,GCDFTZ,GCDEND,XINTS,XINTL
     C ,FLUX,CY12(5),DMXA(24),DMX0,CYRAD(5)
      COMMON /FRQ/ FREL(12),FREL5(11,7),FW5(11,7),MAXF,MF,KOF,FREQ
     A, JKF,FXEMAX
C RAY MODES FOR DISTANCE GHOP,SEE SUBROUTINE CURMUF
      COMMON/MODES/ DELMOD(9),UTMOD(9),ABPS(9),FLDST(9),FSLOS(9)
     1,GRLOS(9),TLOSS(9),XLOSS(9),DELMD1(9),UTMD1(9),KANGLE(12)
     2,DBLOS(12),DBU(12),MODE(12),NHP(12),KANGLA(24,12)
     3,MODEA(24,12),KANGL4(4,12),KDBU4(4,12),DBU4(4,12),MODE4(4,12)
     4,NHP4(4,12),KODEA(24,12)
       character*4 MODE,MODEA,MODE4
      COMMON/MUFS/ EMUF(24,3),F2MUF(24,6),ALLMUF(24),EFMUF(24),FOT(24)
     A ,FOT1(24),XLUF(24),ZLUF(24),OPMUF(24),OPMUF1(24),FU(24),FL(24)
     B, KFN,LUFC,NLOOP,ACT1,DXL,XMODE,FX,PR
      COMMON /TNOISE/BDWTH,JBW,JRSN,LUF,MAN,RLUF,RSN,XSN(2),YNOISE
      INDL=0
      QREL=PR
      IF(QREL.GT.RLUF) GO TO 301
      ACT2=1.0
      GO TO 302
  301 ACT2=-1.0
C..... SET INDL=1 IF RELIABILITY > SPECIFIED VALUE OF 0.5 FOR LUF CALC.
      INDL=1
  302 IF(DXL.LE.0.1.OR.ABS(QREL-RLUF).LE.0.01) GO TO 303
      IF((ACT1*ACT2).LT.0.0) DXL=DXL/2.0
      FX=FX+ACT2*DXL
      IF(FX.LT.(FLOW-1.0).OR.FX.GT.FHIGH.OR.FX.GE.QOPMUF) GO TO 304
      ACT1=ACT2
      IF(NLOOP.GE.35) GO TO 304
      FREQ=FX
      RETURN
  303 XLUF1=FX
      IF(FX.LT.2.0) XLUF1=2.0
      GO TO 305
C..... SET LUF TO OPMUF IF NO VALUE FOUND UNLESS REQ'D REL
C..... EXCEEDED DURING ITERATION,THEN SET LUF = FLOW (MHz)
  304 XLUF1=-QOPMUF      !  negative used to FLAG Req Rel not met!
      IF(INDL.EQ.1) XLUF1=FLOW
  305 CONTINUE
      KFN=12
      LUFC=0
C.....FOLLOWING DETERMINATION OF THE LUF RESTORE,PRIOR TO THE CALC.
C.....OF SHORT DISTANCE METHOD FIELD STRENGTHS ETC,ORIGINAL ORDER
C.....OF ELEVATIONS AND HOP COUNT
      IF(GCDKM.LT.GCDEND) THEN
        DO 306 J9=1,9
        DELMOD(J9)=DELMD1(J9)
        UTMOD(J9)=UTMD1(J9)
  306   CONTINUE
      END IF
      RETURN
      END
c------------------------------------------------------------
