c###sigdis.for
      SUBROUTINE SIGDIS
C.... VERSION 10.APRIL.92
      CHARACTER*40 VERSN
      COMMON/MUFS/ EMUF(24,3),F2MUF(24,6),ALLMUF(24),EFMUF(24),FOT(24)
     A,FOT1(24),XLUF(24),ZLUF(24),OPMUF(24),OPMUF1(24),FU(24),FL(24)
     B, KFN,LUFC,NLOOP,ACT1,DXL,XMODE,FX,PR
      COMMON/CON/D2R,DCL,GAMA,PI,PI2,PIO2,R2D,RZ,VOFL
      COMMON /DON/AMIN,AMIND,BTR,BTRD,BRTD,GCD,GCDKM,PWR,XPW,APW
     A ,RLAT,RLATD,RLONG,RLONGD,SSN,TLAT,TLATD,TLONG,TLONGD,PLAT,PLONG
     B ,PGLAT,ACAV,ASM,FEAV,GMT,VERSN,XLZ,GCDFTZ,GCDEND,XINTS,XINTL
     C ,FLUX,CY12(5),DMXA(24),DMX0,CYRAD(5)
      COMMON /FRQ/ FREL(12),FREL5(11,7),FW5(11,7),MAXF,MF,KOF,FREQ
     A, JKF,FXEMAX
      COMMON/GEOG/ABIY(5),CLAT(5),CLONG(5),CLCK(5),EPSPAT(5),F2M3(5)
c>>(b)WP-6A SEPT. 93 MODS add 2 lines REMOVE 1 LINE
     A,FI(3,5),GLAT(5),GMDIP(5),GYZ100(5),GYR100,GYZ300(5),HPF2(5),RD(5)
     B,SIGPAT(5),CYCEN(5)
CX   A,FI(3,5),GLAT(5),GMDIP(5),GYZ(5),HPF2(5),RD(5),SIGPAT(5),CYCEN(5)
c>>(b)WP-6A SEPT. 93 MODS end of change
      character*4 IRLAT,IRLONG,ITLAT,ITLONG,IRCVR,ITRANS
      COMMON /ION/ IRLAT,IRLONG,ITLAT,ITLONG,IRCVR(5),ITRANS(5),IT,ITRUN
     A,IT1,IT2,ITSTEP,KM,IA,METHOD,ICON,NPSL,NYEAR,NPAGO,ICGM
      COMMON / FILES / LUI,LUO,LU2,LU5,LU6,LU8,LU16,LU61,LU7,LU15
      GLAV=0.0
C.....SET NUMBER OF IONOSPHERES KM(= max # of control pts. for given range)
c>>(e)WP-6A SEPT. 93 MODS replace 'XKF' by 'XKM' throughout this subroutine
      XKM=KM
      XADJ=0.0
      AC=0.0
      FEAV=0.0
      DO 115 K=1,KM
C.....ABSORPTION INDEX
C.....SYSTEM LOSS TABLE
      DUMMY1=GLAT(K)
      DUMMY2=CLCK(K)
      NN=2
      IF(GCDKM.GT.2500.) NN=5
      CALL SYSSY(DUMMY1,DUMMY2,NN,ADJ)
ccc      write(luo,1) glat(k)/.0174533,clck(k),gcdkm,nn,adj
ccc1     format('sigdis=',f10.4,f8.2,f10.2,i3,f8.3)
C.....MEDIAN
      XADJ=XADJ+ADJ
C.....E CRITICAL
      FEAV=FEAV+FI(1,K)
C.....ABSORBTION INDEX
ccc      AC =AC  +ABIY(K)     !  absorption not calculated in LUFFY
C.....GEOMAGNETIC LATITUDE
      GLAV=GLAV+ABS(GLAT(K))
  115 CONTINUE
C.....BEGIN SECTION TO SAVE THE AVERAGE VALUES
      GLAV= GLAV/XKM
      AGLAT=GLAV
      ACAV= AC/XKM
      FEAV= FEAV/XKM
      ADJ=XADJ/XKM
      ASM=ADJ-9.
      ASM=AMAX1(0.0,ASM)
C.....END SECTION TO SAVE THE AVERAGE VALUES
      RETURN
      END
