c###timvar.for
      SUBROUTINE TIMVAR
C.....VERSION 10.JUN.95
      CHARACTER*40 VERSN
      COMMON /CON/D2R, DCL, GAMA, PI, PI2, PIO2, R2D, RZ, VOFL
      COMMON /DON/AMIN,AMIND,BTR,BTRD,BRTD,GCD,GCDKM,PWR,XPW,APW
     A ,RLAT,RLATD,RLONG,RLONGD,SSN,TLAT,TLATD,TLONG,TLONGD,PLAT,PLONG
     B ,PGLAT,ACAV,ASM,FEAV,GMT,VERSN,XLZ,GCDFTZ,GCDEND,XINTS,XINTL
     C ,FLUX,CY12(5),DMXA(24),DMX0,CYRAD(5)
      COMMON/GEOG/ABIY(5),CLAT(5),CLONG(5),CLCK(5),EPSPAT(5),F2M3(5)
c>>(b)WP-6A SEPT. 93 MODS add 2 lines REMOVE 1 LINE
     A,FI(3,5),GLAT(5),GMDIP(5),GYZ100(5),GYR100,GYZ300(5),HPF2(5),RD(5)
     B,SIGPAT(5),CYCEN(5)
CX   A,FI(3,5),GLAT(5),GMDIP(5),GYZ(5),HPF2(5),RD(5),SIGPAT(5),CYCEN(5)
c>>(b)WP-6A SEPT. 93 MODS end of change
      character*4 IRLAT,IRLONG,ITLAT,ITLONG,IRCVR,ITRANS
      COMMON /ION/ IRLAT,IRLONG,ITLAT,ITLONG,IRCVR(5),ITRANS(5),IT,ITRUN
     A,IT1,IT2,ITSTEP,KM,IA,METHOD,ICON,NPSL,NYEAR,NPAGO,ICGM
      COMMON /SOL/ DECL12(12),EQT12(12),DECL,EQT,MONTH,IMON(12)
c>>(a)WP-6A SEPT. 93 MODS modify comment, thence add 3 lines remove 1 line
C.....apparent long. difference of sub-solar point(equat of-time included)
      SSL=(15. * GMT-180. - EQT) * D2R
CX    SSL=(15. * GMT-180.) * D2R
      DO 155 II=1, KM
C.....SAMPLE AREA LONGITUDE AND LATITUDE
      CENLG=CLONG (II)
      CENLAT=CLAT (II)
C.... CALC. LATITUDE OF SUB-SOLAR ZENITH POINT ,SSP
      SSP=DECL*D2R
c>>(a)WP-6A 93 MODS take remove 3 lines then calc. noon solar zenith later
cx      CHI12=CENLAT-SSP
cx      CHI12=ABS(CENLAT-SSP)
cx      CY12(II)=CHI12*R2D
 105  CLOCK=GMT-CENLG / .261799387
      IF(24.-CLOCK)110, 115, 115
 110  CLOCK=CLOCK-24.
      GO TO 125
 115  IF(CLOCK)120, 120, 125
 120  CLOCK=CLOCK+24.
C.....CLCK(II) IS LOCAL MEAN TIME
 125  CLCK (II)=CLOCK
C.....COMPUTE ZENITH ANGLE
      Z=SSL-CENLG
      CYCEN(II)=SIN(CENLAT)*SIN(SSP)+COS(CENLAT)*COS(SSP)*COS(Z)
      CYCEN(II)=ACOS(CYCEN(II)) * R2D
c>>(a)WP-6A SEPT. 93 ADD 4 LINES   (WP 3L RG4 MOD JUNE 95)
C.....COMPUTE  LOCAL MEAN MEAN SOLAR ZENITH ANGLE
       CCHI12=SIN(CENLAT)*SIN(SSP)+COS(CENLAT)*COS(SSP)*COS(-EQT*D2R)
       CHI12=ACOS(CCHI12)
       CY12(II)=CHI12 * R2D
c>>(a)WP-6A SEPT. 93 MODS end of change
 155  CONTINUE
      RETURN
      END
