c###weight.for
      FUNCTION WEIGHT(F,LUF,FOT,OPMUF)
C **** EVALUATE A WEIGHTING FACTOR INDICATING HOW CLOSE A GIVEN
C **** FREQUENCY F IS TO THE OPTINUM WORKING FREQUENCY FOT
C **** RI IS EVALUATED BETWEEN THE LOWEST WORKING FREQUENCY LUF (WHERE
C **** RI=0),THROUGH THE FOT (RI=1) TO THE OPERATIONAL WORKING
C **** FREQUENCY OPMUF (RI=0).
C **** OUTSIDE THIS RANGE RI=0
      REAL LUF
      IF(LUF.EQ.OPMUF) GO TO 3
      IF(F.GT.FOT) GO TO 2
      XF1=FOT-LUF
      IF(XF1.LE.0.0) GO TO 3
      YF1=(FOT-F)/XF1
      WEIGHT=1.0-YF1*YF1
      WEIGHT=AMAX1(WEIGHT,-1.0)
      RETURN
    2 XF2=OPMUF-FOT
      YF2=(F-FOT)/XF2
      WEIGHT=1.0-YF2*YF2
      WEIGHT=AMAX1(WEIGHT,-1.0)
      RETURN
    3 WEIGHT=-1.0
      RETURN
      END
