c###xposit.for
      SUBROUTINE XPOSIT(LOCAT)
C.....VERSION 21.MAR.88
C.....CREATES TRANSMITTER(LOCAT=1) OR RECEIVER(LOCAT=2) CONTROL CARD.
 
      INTEGER*4 LOCAT
      CHARACTER*1 BUF(80),TXNAME(20),D,M,XX,DEGM,CPO,CPL,BLANK
      COMMON/PARAM/BUF,K1,K2,LK1,LK2
      COMMON / FILES / LUI,LUO,LU2,LU5,LU6,LU8,LU16,LU61,LU7,LU15
      DATA D/'D'/,M/'M'/,BLANK/' '/
C..... GET USER INPUT INTO TEXT FORM
      READ(LU5,50,END=78) BUF
   50 FORMAT(80A1)
      K1=7
      K2=26
C ..... READ TRANSMITTER/RECEIVER TEXT NAME
      K20=0
      DO 100 KC=K1,K2
      K20=K20+1
      TXNAME(K20)=BUF(KC)
  100 CONTINUE
      DEGM=D
      K1=37
      K2=41
C ..... READ UNIT OF TRANSMITTER/RECEIVER CO-ORDINATES
C ..... D=DECIMAL DEGREES,M=DEGREES AND MINUTES(DEFAULT=D)
      DO 101 K0=K1,K2
      XX=BUF(K0)
      IF(XX.NE.BLANK) GO TO 102
  101 CONTINUE
  102 IF(XX.EQ.D.OR.XX.EQ.M) DEGM=XX
      K1=54
      K2=60
      CALL CORDS(90.0,X)
      TLA=X
C ..... CPL,CPO COMPAS POINTING (I.E. N,S, OR E,W RESP.)
      CPL=BUF(80)
      K1=67
      K2=73
C ..... READ TRANSMITTER OR RECEIVER CO-ORDINATES
      CALL CORDS(360.0,X)
      TLO=X
      CPO=BUF(80)
C ..... CPL,CPO COMPAS POINTING (I.E. N,S, OR E,W RESP.)
C ..... IF LOCAT=1 WRITE TRANSMITTER CIRCUIT CARD
C ..... IF LOCAT=2 WRITE RECEIVER CIRCUIT CARD
      IF(LOCAT.EQ.1) WRITE(LU15,201) TXNAME,TLA,CPL,TLO,CPO,DEGM
      IF(LOCAT.EQ.2) WRITE(LU15,202) TXNAME,TLA,CPL,TLO,CPO,DEGM
  201 FORMAT('TRANS     ',20A1,2(F7.2,A1,3X),5X,A1)
  202 FORMAT('RECVR     ',20A1,2(F7.2,A1,3X),5X,A1)
      RETURN
   78 STOP 78
      END
