c###xten3.for
      FUNCTION XTEN3(TEN,X1,X2,X3)
C.....FUNCTION DETERMINES THE RSS SUM OF THE THREE QUANTIDIES X1,X2,X3
      XTEN3=TEN*ALOG10(TEN**(X1/TEN)+TEN**(X2/TEN)+TEN**(X3/TEN))
      RETURN
      END
